version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:master

        working_directory: /go/src/github.com/byuoitav/pi-designation-microservice

        steps:
            - checkout
            - setup_remote_docker
            - run: |
                make deps
                make build
                make test
                make docker
                ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1 $CIRCLE_BRANCH
