version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:experimental

        working_directory: /go/src/github.com/byuoitav/configuration-database-microservice

        steps:
            - checkout
            - setup_remote_docker
            - run: make deps
            - run: make build
            - run: make test
            - run: make docker
            - run: ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1 $CIRCLE_BRANCH
