version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:latest

        working_directory: /go/src/github.com/byuoitav/configuration-database-microservice

        steps:
            - checkout
            - run: cd .. && rm -rf authmiddleware && rm -rf av-api
            - setup_remote_docker
            - run: make deps
            - run: make build
            - run: make test
            - run: make docker
            - run: ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1 $CIRCLE_BRANCH
